/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface CrowdsaleContract extends Truffle.Contract<CrowdsaleInstance> {
  "new"(
    initialSupply: number | BN | string,
    meta?: Truffle.TransactionDetails
  ): Promise<CrowdsaleInstance>;
}

type AllEvents = never;

export interface CrowdsaleInstance extends Truffle.ContractInstance {
  rate(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  token(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    rate(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    token(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
