/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AlyraERC20TokenContract } from "./AlyraERC20Token";
import { BankContract } from "./Bank";
import { ContactsContract } from "./Contacts";
import { CrowdsaleContract } from "./Crowdsale";
import { ERC20Contract } from "./ERC20";
import { ERC20TokenContract } from "./ERC20Token";
import { Ex1Contract } from "./Ex1";
import { GuessAndWinContract } from "./GuessAndWin";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { NotesContract } from "./Notes";
import { OwnableContract } from "./Ownable";
import { PeopleContract } from "./People";
import { RandomContract } from "./Random";
import { SavingContract } from "./Saving";
import { TimeContract } from "./Time";
import { WhitelistContract } from "./Whitelist";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AlyraERC20Token"): AlyraERC20TokenContract;
      require(name: "Bank"): BankContract;
      require(name: "Contacts"): ContactsContract;
      require(name: "Crowdsale"): CrowdsaleContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC20Token"): ERC20TokenContract;
      require(name: "Ex1"): Ex1Contract;
      require(name: "GuessAndWin"): GuessAndWinContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "Notes"): NotesContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "People"): PeopleContract;
      require(name: "Random"): RandomContract;
      require(name: "Saving"): SavingContract;
      require(name: "Time"): TimeContract;
      require(name: "Whitelist"): WhitelistContract;
    }
  }
}

export {
  AlyraERC20TokenContract,
  AlyraERC20TokenInstance,
} from "./AlyraERC20Token";
export { BankContract, BankInstance } from "./Bank";
export { ContactsContract, ContactsInstance } from "./Contacts";
export { CrowdsaleContract, CrowdsaleInstance } from "./Crowdsale";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC20TokenContract, ERC20TokenInstance } from "./ERC20Token";
export { Ex1Contract, Ex1Instance } from "./Ex1";
export { GuessAndWinContract, GuessAndWinInstance } from "./GuessAndWin";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { NotesContract, NotesInstance } from "./Notes";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { PeopleContract, PeopleInstance } from "./People";
export { RandomContract, RandomInstance } from "./Random";
export { SavingContract, SavingInstance } from "./Saving";
export { TimeContract, TimeInstance } from "./Time";
export { WhitelistContract, WhitelistInstance } from "./Whitelist";