/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as adminSol from "./Admin.sol";
export type { adminSol };
import type * as exercice1Sol from "./Exercice1.sol";
export type { exercice1Sol };
import type * as inheritageSol from "./Inheritage.sol";
export type { inheritageSol };
export type { AlyraERC20Token } from "./AlyraERC20Token";
export type { Bank } from "./Bank";
export type { Crowdsale } from "./Crowdsale";
export type { GuessAndWin } from "./GuessAndWin";
export type { Notes } from "./Notes";
export type { People } from "./People";
export type { Random } from "./Random";
export type { SPA } from "./SPA";
export type { Saving } from "./Saving";
export type { SimpleStoragePayable } from "./SimpleStoragePayable";
export type { Time } from "./Time";
export type { Whitelist } from "./Whitelist";
