/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deployedSol from "./Deployed.sol";
export type { deployedSol };
import type * as lyceeSol from "./Lycee.sol";
export type { lyceeSol };
