/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface TimeContract extends Truffle.Contract<TimeInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<TimeInstance>;
}

type AllEvents = never;

export interface TimeInstance extends Truffle.ContractInstance {
  getTime(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  methods: {
    getTime(txDetails?: Truffle.TransactionDetails): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
