/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as corrections from "./corrections";
export type { corrections };
import type * as exercices from "./exercices";
export type { exercices };
import type * as samples from "./samples";
export type { samples };
