/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Authorized = ContractEventLog<{
  _address: string;
  0: string;
}>;

export interface Whitelist extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Whitelist;
  clone(): Whitelist;
  methods: {
    authorize(_address: string): NonPayableTransactionObject<void>;
  };
  events: {
    Authorized(cb?: Callback<Authorized>): EventEmitter;
    Authorized(options?: EventOptions, cb?: Callback<Authorized>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Authorized", cb: Callback<Authorized>): void;
  once(
    event: "Authorized",
    options: EventOptions,
    cb: Callback<Authorized>
  ): void;
}
