/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { OwnableContract } from "./Ownable";
import { VotingContract } from "./Voting";
import { VotingAlyraContract } from "./VotingAlyra";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Ownable"): OwnableContract;
      require(name: "Voting"): VotingContract;
      require(name: "VotingAlyra"): VotingAlyraContract;
    }
  }
}

export { OwnableContract, OwnableInstance } from "./Ownable";
export { VotingContract, VotingInstance } from "./Voting";
export { VotingAlyraContract, VotingAlyraInstance } from "./VotingAlyra";
